### ISSUE TITLE
请问已经在生产中实际使用了吗？目前貌似只支持H、V、Z布局哈?

### ISSUE THREAD

**Issue by xhl916235259** [scubers/puyopuyo#1]

**Comment by scubers** [comment]
已经在自己公司的项目进行初步的开始使用了，还未正式发版，正在慢慢替换API，并进行功能增加和测试。现在已经有了Flow布局。敬请期待。请问再哪里看到找到这个仓库的呢？

**Comment by xhl916235259** [comment]
嗯 嗯，我在欧阳大哥的QQ群里面看你讨论过你这个库，然后看了还挺有意思的，期待正式版。



------------------ 原始邮件 ------------------
发件人: "jrw0ng"<notifications@github.com>; 
发送时间: 2019年9月3日(星期二) 晚上11:51
收件人: "scubers/puyopuyo"<puyopuyo@noreply.github.com>; 
抄送: "Dragon"<916235259@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [scubers/puyopuyo] 请问已经在生产中实际使用了吗？目前貌似只支持H、V、Z布局哈? (#1)




已经在自己公司的项目进行初步的开始使用了，还未正式发版，正在慢慢替换API，并进行功能增加和测试。现在已经有了Flow布局。敬请期待。请问再哪里看到找到这个仓库的呢？
