### ISSUE TITLE
如何让子视图撑满父视图？

### ISSUE THREAD

**Issue by lihanst** [scubers/puyopuyo#2]
比如 View { HBox { label, label } }

**Comment by scubers** [comment]
首先，若最外层的View只是一个普通View，需要有具体的大小。
size(.fill, .fill) 则意味着填充所有的剩余空间。.fill 其实是 .ratio(1)

在Box中，若存在多个.ratio, 则具体分摊的的剩余空间需要是  (当前Ratio / 总ratio) * 剩余空间。此过程只会发生在主轴剩余空间。

```
UIView().attach {
  HBox().attach($0) {
    UILabel().attach($0)
      .text("1")
      .size(.fill, .fill)

    UILabel().attach($0)
      .text("2")
      .size(.fill, .fill)
  }
  .size(.fill, .fill)
}
```
